trigger:
- none #se usa none para que al momento de mandar los cambios no se publique automaticamente
 #pero por defecto seria fix-back-end

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    mavenPomFile: 'licor-golden-backend-config-backend/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    preserveTimestamp: true
- task: PublishBuildArtifacts@1
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'